version: '3.9'


services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Paroli1!
        - POSTGRES_DB=movies
    ports:
        - "5433:5432"